# Generated by Django 3.1.2 on 2021-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clinic', models.PositiveIntegerField()),
                ('id_physician', models.PositiveIntegerField()),
                ('id_patient', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
