BASE_URL = 'https://5f71da6964a3720016e60ff8.mockapi.io/v1'

PHYSICIANS_URL = '/physicians/'
PHYSICIANS_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGh5c2ljaWFucyJ9.Ei58MtFFGBK4uzpxwnzLxG0Ljdd-NQKVcOXIS4UYJtA'
PHYSICIANS_TIMEOUT = 4
PHYSICIANS_RETRY = 2
PHYSICIANS_TTL = 48

CLINICS_URL = '/clinics/'
CLINICS_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoiY2xpbmljcyJ9.r3w8KS4LfkKqZhOUK8YnIdLhVGJEqnReSClLCMBIJRQ'
CLINICS_TIMEOUT = 5
CLINICS_RETRY = 3
CLINICS_TTL = 72

PATIENTS_URL = '/patients/'
PATIENTS_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGF0aWVudHMifQ.Pr6Z58GzNRtjX8Y09hEBzl7dluxsGiaxGlfzdaphzVU'
PATIENTS_TIMEOUT = 3
PATIENTS_RETRY = 2
PATIENTS_TTL = 12

METRICS_URL = '/metrics'
METRICS_TOKEN = 'Bearer SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
PATIENTS_TIMEOUT = 6
PATIENTS_RETRY = 5

